# After changing this file, check it on:
#   http://lint.travis-ci.org/

# to test different versions of python, check the numpy travis file on:
#   https://github.com/numpy/numpy/blob/master/.travis.yml

sudo: required
language: python

# which python versions to test
python:
  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly"

virtualenv:
    system_site_packages: true

# command before installation
before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install libblas-dev liblapack-dev
#  - sudo apt-get install libcr-dev mpich2
#  - sudo apt-get install mpich libmpich-dev # libhdf5-mpich-dev
  - sudo apt-get install libopenmpi-dev openmpi-bin # libhdf5-openmpi-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

before_script:
  - mkdir __pytest__

# command to run tests
script:
  - cd __pytest__
  - python -m pytest ../tests/parser/test_headers.py
  - python -m pytest ../tests/parser/test_openmp.py
  - python -m pytest ../tests/parser/test_openacc.py
  - python -m pytest ../tests/syntax/test_syntax.py
  - python -m pytest ../tests/semantic/test_semantic.py
  - python -m pytest ../tests/codegen/test_codegen.py
  - python -m pytest ../tests/errors/test_errors.py
  - python -m pytest ../tests/warnings/test_warnings.py
  - python -m pytest ../tests/preprocess/test_preprocess.py
  - python -m pytest ../tests/epyccel -v
# this test must be executed with python, since we are calling mpif90 inside it
  - python ../tests/internal/test_internal.py
  - python ../tests/external/test_external.py
  - python ../tests/macro/test_macro.py
#  - python ../tests/test_pyccel.py --execute
#  - python ../tests/test_pyccel_openmp.py --openmp --execute
#  - python ../tests/test_pyccel_lapack.py --libs='blas lapack' --execute
#  - python ../tests/test_pyccel_mpi.py --compiler=mpif90
  - cd -

after_script:
  - rm -rf __pytest__
