# After changing this file, check it on:
#   http://lint.travis-ci.org/

# to test different versions of python, check the numpy travis file on:
#   https://github.com/numpy/numpy/blob/master/.travis.yml

sudo: required
language: python

# which python versions to test
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly"

virtualenv:
    system_site_packages: true

# command before installation
before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install libcr-dev mpich2

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
#  - pytest # or py.test for Python versions 3.5 and below
  - pytest tests/ast/test_ast.py
  - pytest tests/parser/test_headers.py
  - pytest tests/parser/test_openmp.py
  - pytest tests/parser/test_openacc.py
  - pytest tests/syntax/test_syntax.py
  - pytest tests/semantic/test_semantic.py
  - pytest tests/codegen/test_codegen.py
  - python tests/epyccel/test_epyccel.py  
#  - python tests/test_pyccel.py --execute
#  - python tests/test_pyccel_openmp.py --openmp --execute
#  - python tests/test_pyccel_lapack.py --libs='blas lapack' --execute
#  - python tests/test_pyccel_mpi.py --compiler=mpif90
