name: 'Linux installation commands'

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        apt-get update
      shell: bash
    - name: Install fortran
      run:
        apt-get -y install gfortran
      shell: bash
    - name: Install LaPack
      run:
        apt-get -y install libblas-dev liblapack-dev
      shell: bash
    - name: Install MPI
      run: |
        DEBIAN_FRONTEND=noninteractive
        apt-get -y install libopenmpi-dev openmpi-bin
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
      shell: bash
    - name: Install OpenMP
      run:
        apt-get -y install libomp-dev libomp5
      shell: bash
    - name: Install Valgrind
      run:
        apt-get -y install valgrind
      shell: bash
