name: 'Linux installation commands'

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        sudo apt-get update
      shell: bash
    - name: Install fortran
      run:
        sudo apt-get -y install gfortran
      shell: bash
    - name: Install python
      run:
        sudo apt-get -y install python3-dev
      shell: bash
    - name: python as python3
      run:
        sudo apt-get -y install python-is-python3
      shell: bash
    - name: Install Pip
      run:
        sudo apt-get -y install python3-pip
      shell: bash
    - name: Install LaPack
      run:
        sudo apt-get -y install libblas-dev liblapack-dev
      shell: bash
    - name: Install MPI
      run: |
        DEBIAN_FRONTEND=noninteractive TZ=Africa/Morocco sudo apt-get -y install libopenmpi-dev openmpi-bin
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
      shell: bash
    - name: Install OpenMP
      run:
        sudo apt-get -y install libomp-dev libomp5
      shell: bash
    - name: Install Valgrind
      run:
        sudo apt-get -y install valgrind
      shell: bash
