name: Pyccel tests

on:
  pull_request:
    branches: [ master ]

jobs:
  #Linux:

  #  runs-on: ubuntu-latest

  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Set up Python 3.7
  #      uses: actions/setup-python@v2
  #      with:
  #        python-version: 3.7
  #    - name: Install dependencies
  #      uses: ./.github/actions/linux_install
  #    - name: Install python dependencies
  #      uses: ./.github/actions/pip_installation
  #    - name: Coverage install
  #      uses: ./.github/actions/coverage_install
  #    - name: Fortran/C tests with pytest
  #      uses: ./.github/actions/pytest_run
  #    - name: Python tests with pytest
  #      uses: ./.github/actions/pytest_run_python
  #    - name: Parallel tests with pytest
  #      uses: ./.github/actions/pytest_parallel
  #    - name: Test with valgrind for memory leaks
  #      uses: ./.github/actions/valgrind_run
  #    - name: Collect coverage information
  #      continue-on-error: True
  #      uses: ./.github/actions/coverage_collection
  #    - name: Run codacy-coverage-reporter
  #      uses: codacy/codacy-coverage-reporter-action@master
  #      continue-on-error: True
  #      with:
  #        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  #        coverage-reports: cobertura.xml

  Windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
            # The second most recent version is used as
            # setup-python installs the most recent patch
            # which leads to linking problems as there are
            # 2 versions of python3X.a and the wrong one
            # is chosen
            python-version: 3.7
      - name: Install dependencies
        uses: ./.github/actions/windows_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Lapack test pwsh
        run: |
          ls C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\lib
          pyccel lapack_subroutine.py --verbose
          echo "Calling"
          python -c "from lapack_subroutine import dgetri_test; from numpy import eye; N = 4; A = eye(N,dtype='float64',order='F'); dgetri_test(A); print(A)"
          echo "Executing"
          lapack_subroutine.exe
        shell: powershell
        working-directory: ./tests/pyccel/scripts
      - name: Lapack test
        run: |
          ls C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib
          pyccel lapack_subroutine.py --verbose
          ls
          pwd
          echo "Calling"
          python -c "from lapack_subroutine import dgetri_test; from numpy import eye; N = 4; A = eye(N,dtype='float64',order='F'); dgetri_test(A); print(A)"
          echo "Executing"
          /d/a/pyccel/pyccel/tests/pyccel/scripts/lapack_subroutine.exe
        shell: bash
        working-directory: ./tests/pyccel/scripts
      - name: Fortran/C tests with pytest
        uses: ./.github/actions/pytest_run
      - name: Python tests with pytest
        uses: ./.github/actions/pytest_run_python
      - name: Parallel tests with pytest
        uses: ./.github/actions/pytest_parallel

  #MacOSX:

  #  runs-on: macos-latest

  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Set up Python 3.10
  #      uses: actions/setup-python@v2
  #      with:
  #        python-version: '3.10'
  #    - name: Install dependencies
  #      uses: ./.github/actions/macos_install
  #    - name: Install python dependencies
  #      uses: ./.github/actions/pip_installation
  #    - name: Fortran/C tests with pytest
  #      uses: ./.github/actions/pytest_run
  #    - name: Python tests with pytest
  #      uses: ./.github/actions/pytest_run_python
  #    - name: Parallel tests with pytest
  #      uses: ./.github/actions/pytest_parallel
